apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  #local:
    #push: false
  googleCloudBuild:
    projectId: noted-robot-231086 
  artifacts:
    - image: eu.grc.io/noted-robot-231086/auth
      context: auth
      docker: 
        dockerfile: Dockerfile
      sync:
        manual:
         - src: 'src/**/*.ts'
           dest: .
    - image: eu.grc.io/noted-robot-231086/client
      context: client
      docker: 
        dockerfile: Dockerfile
      sync:
        manual:
         - src: '**/*.js'
           dest: .
    - image: eu.grc.io/noted-robot-231086/tickets
      context: tickets
      docker: 
        dockerfile: Dockerfile
      sync:
        manual:
         - src: 'src/**/*.ts'
           dest: .
    - image: eu.grc.io/noted-robot-231086/orders
      context: orders
      docker: 
        dockerfile: Dockerfile
      sync: 
        manual: 
          - src: 'src/**/*.ts'
            dest: .


